language: dart
os:
  - linux
sudo: required
dist: trusty
dart:
- 2.1.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b master --depth 1
  - ./flutter/bin/flutter doctor
script:
  - pub get
  - pub run test_coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache