name: lumberdash
description: >-
  Do you need logs? Lumberdash is the answer! Simple and extensible 
  API that allows you to create your plugins.
version: 1.0.2
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/lumberdash

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.4.0
  test_coverage: ^0.2.0
  mockito: ^4.0.0