name: example
description: Example project for Lumberjack
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  lumberdash: ^2.1.0
  colorize_lumberdash:
    path: ../

dev_dependencies:
