name: example
description: Example project for Lumberdash
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lumberdash: ^3.0.0
  firebase_lumberdash:
    path: ../

dev_dependencies:

