name: example
description: Example project for sentry_lumberdash
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sentry: ^6.0.0-0
  lumberdash: ^3.0.0
  sentry_lumberdash:
    path: ../

