name: example
description: Example project for Lumberjack
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  sentry: ^4.0.0
  lumberdash: ^2.1.0
  sentry_lumberdash:
    path: ../

dev_dependencies:

