name: lumberdash
description: >-
  Do you need logs? Lumberdash is the answer! Simple and extensible 
  logging API, it allows you to create and consume different that will
  cover all your logging needs.
version: 3.0.0
authors:
  - BMW Group <flutter-dev@bmwgroup.com>
repository: https://github.com/bmw-tech/lumberdash
issue_tracker: https://github.com/bmw-tech/lumberdash/issues
homepage: https://bmw-tech.github.io/lumberdash/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.0
