name: sentry_lumberdash
description: >-
  Lumberdash plugin that sends your logs to Sentry with the proper
  severity level
version: 3.1.0
authors:
  - BMW Group <flutter-dev@bmwgroup.com>
repository: https://github.com/bmw-tech/lumberdash
issue_tracker: https://github.com/bmw-tech/lumberdash/issues
homepage: https://bmw-tech.github.io/lumberdash/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lumberdash: ^3.0.0
  meta: ^1.3.0
  sentry: ^5.0.0

dev_dependencies:
  test: ^1.16.5
  mockito: ^5.0.0
