name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_dart:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        package: ["lumberdash","colorize_lumberdash","file_lumberdash","print_lumberdash","sentry_lumberdash"]
        version: ["latest",]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: dart pub get
      
      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dart analyze --fatal-infos --fatal-warnings lib
        
      - name: Activate coverage
        run: pub global activate coverage
      
      - name: Run Tests
        working-directory: ${{ matrix.package }}
        run: pub run test test
      
      - name: Start Observatory
        working-directory: ${{ matrix.package }}
        run: dart
           --disable-service-auth-codes
           --pause-isolates-on-exit
           --enable-vm-service=9822
           --enable-asserts
           test/all_tests.dart &

      - name: Collect coverage
        working-directory: ${{ matrix.package }}
        run: nohup pub global run coverage:collect_coverage
          --port=9822
          --out=coverage/coverage.json
          --wait-paused
          --resume-isolates

      - name: Generate Report
        working-directory: ${{ matrix.package }}
        run: pub global run coverage:format_coverage
          --lcov
          --in=coverage/coverage.json
          --out=coverage/lcov.info
          --packages=.packages
          --report-on=lib

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info
  build_flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["firebase_lumberdash"]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info